### ISSUE TITLE
tests failing with newer pydantic version

### ISSUE THREAD

**Issue by danyilq** [marqo-ai/py-marqo#116]
with pydantic 2.0+ TestBulkSearch fails returning 
`Field required [type=missing, input_value={'http_operation': 'post'...': 'my-test-index-1'}]}}, input_type=dict]`

tests doesn't fail with older pydantic versions

**Comment by wanliAlex** [comment]
fixed in this PR 
https://github.com/marqo-ai/py-marqo/pull/117
