### ISSUE TITLE
Permission request to redistribute to Nixpkgs

### ISSUE THREAD

**Issue by naufik** [marqo-ai/py-marqo#247]
Hi all,

I'd like to request permission to distribute the Marqo client through the Nixpkgs repository. Nix is a polyglot build tool and package management tool that focuses on reproducible software and OS builds, and Nixpkgs is the repository that supplies packages into the package manager. (More info: https://nixos.org)

There's currently to package `dspy` which requires Marqo as a dependency: https://github.com/NixOS/nixpkgs/issues/323924. I've already got a personal "package" working as I've been experimenting personally and so I can submit that to them. There are still some upstream issues, but a first step in packaging would be packaging its dependencies.

Nix directly interfaces with PyPi and GitHub so Nixpkgs wouldn't be hosting Marqo releases, instead they will be hosting definitions for the package manager to download from PyPi (similar to homebrew formulae).

I believe redistribution is allowed by the Apache 2.0 license, I just want to have explicit permission to be safe given that the pypi package uses your trade name.

Please let me know if this is OK, and additionally:
- If you'd like me to register one of you as a maintainer for the package (I will be maintaining it as well)
- A CLA, if required

Thank you

**Comment by pandu-k** [comment]
@naufik - go for it! Thanks for letting us know!

**Comment by naufik** [comment]
Sweet! Thank you
